import { useEffect, useRef, useState } from 'react'
import type { ResumeDocument } from '@rb/core/types/document'
import {
  sampleCvDocument,
  sampleInternationalResumeDocument,
  sampleResumeDocument,
} from '@rb/fixtures'
import { useSamplePdfPreview } from '@/components/landing/samplePdf'
import { PdfSkeleton } from '@/components/landing/PdfSkeleton'

/**
 * Example documents: real PDFs from the same engine, rendered lazily when
 * the section scrolls into view. Fictional people, real output.
 */

interface ExampleDoc {
  id: string
  title: string
  sub: string
  chips: string[]
  document: ResumeDocument
}

const EXAMPLES: ExampleDoc[] = [
  {
    id: 'malaysia-resume',
    title: 'Malaysia corporate resume',
    sub: 'Jordan Tan, software engineer',
    chips: ['A4', 'ATS-strict'],
    document: sampleResumeDocument,
  },
  {
    id: 'international-resume',
    title: 'International resume',
    sub: 'Alex Morgan, senior software engineer',
    chips: ['US Letter', 'Classic'],
    document: sampleInternationalResumeDocument,
  },
  {
    id: 'academic-cv',
    title: 'Academic CV',
    sub: 'Jordan Tan, complete career record',
    chips: ['A4', 'Academic'],
    document: sampleCvDocument,
  },
]

function useInView<T extends Element>() {
  const ref = useRef<T>(null)
  const [inView, setInView] = useState(
    () => typeof IntersectionObserver === 'undefined',
  )

  useEffect(() => {
    const el = ref.current
    if (!el || inView) return
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries.some((entry) => entry.isIntersecting)) {
          setInView(true)
          observer.disconnect()
        }
      },
      { rootMargin: '300px' },
    )
    observer.observe(el)
    return () => observer.disconnect()
  }, [inView])

  return { ref, inView }
}

function ExampleCard({ example }: { example: ExampleDoc }) {
  const { ref, inView } = useInView<HTMLDivElement>()
  const { dataUrl, pageCount } = useSamplePdfPreview(example.document, inView)

  return (
    <article
      ref={ref}
      className="rounded-md border border-border bg-card p-4 shadow-[var(--shadow-raised)]"
    >
      <div className="overflow-hidden rounded-sm border border-border bg-muted">
        {dataUrl ? (
          <img
            src={dataUrl}
            alt={`${example.title}: exported PDF`}
            className="w-full"
            loading="lazy"
          />
        ) : (
          <PdfSkeleton />
        )}
      </div>
      <div className="mt-3 flex flex-wrap items-start justify-between gap-2">
        <div className="min-w-0">
          <h3 className="text-[15px] font-semibold text-foreground">{example.title}</h3>
          <p className="mt-0.5 text-xs text-muted-foreground">{example.sub}</p>
        </div>
        <div className="flex flex-wrap gap-1.5">
          {example.chips.map((chip) => (
            <span
              key={chip}
              className="rounded-full border border-border bg-muted px-2.5 py-0.5 text-xs text-muted-foreground"
            >
              {chip}
            </span>
          ))}
          <span className="rounded-full border border-border bg-muted px-2.5 py-0.5 text-xs text-muted-foreground">
            {pageCount ? `${pageCount} page${pageCount === 1 ? '' : 's'}` : '...'}
          </span>
        </div>
      </div>
    </article>
  )
}

export function ExamplesSection() {
  return (
    <section className="border-b border-border">
      <div className="mx-auto max-w-6xl px-5 py-16">
        <h2 className="text-2xl font-semibold tracking-tight">Example documents</h2>
        <p className="mt-2 max-w-2xl text-muted-foreground">
          Real PDFs generated by this app from fictional sample data. Pick a
          style, then make it yours.
        </p>
        <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {EXAMPLES.map((example) => (
            <ExampleCard key={example.id} example={example} />
          ))}
        </div>
      </div>
    </section>
  )
}
